version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  node-app:
    build: ./node-app
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3000:3000"
    command: sh -c "sleep 10 && node index.js"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - node-app